### 多次元配列


In [1]:
import numpy as np

In [7]:
A = np.array([1,2,3,4])
print np.ndim(A) # 次元数
print A.shape    # 配列の形状
print A.shape[0] # 先頭要素の形状

B = np.arange(6).reshape(3,2,1)
print np.ndim(B) # 次元数
print B.shape    # 配列の形状
print B.shape[0] # 先頭要素の形状
print B


1
(4,)
4
3
(3, 2, 1)
3
[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]]


### 内積

In [8]:
A = np.array([[1,2],[3,4]])
print A.shape
B = np.array([[4,3],[2,1]])
print B.shape

print np.dot(A,B)
# [[1*4 + 2*2 , 1*3 + 2*1]
#  [3*4 + 4*2 , 3*3 , 4*1]]

(2, 2)
(2, 2)
[[ 8  5]
 [20 13]]


In [13]:
C = np.arange(6).reshape(3,2)
print C.shape
print C
D = np.array([7,8]).reshape(2,1)
print D.shape
print D
print np.dot(C,D)
# [0*7 + 1*8
#  2*7 + 3*8
#  4*7 + 5*8]


(3, 2)
[[0 1]
 [2 3]
 [4 5]]
(2, 1)
[[7]
 [8]]
[[ 8]
 [38]
 [68]]
